#base Image (OS)
FROM nginx:alpine

#set working directory
WORKDIR /app

#copy the code from host to container
COPY . .

#set environment
ENV 

#LABEL 

RUN 

#Exposing the port
EXPOSE 8080

#
ENTRYPOINT ["pthon3" ]

#serve the Application
CMD ["app.py"]